version: '3.8'

services:
  simple-firewall:
    build: .
    container_name: simple-firewall
    ports:
      - "8080:8080"
    volumes:
      - ./firewall-logs:/app/logs
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped

networks:
  default:
    driver: bridge
