FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Копируем файлы проекта
COPY service-a/ServiceA.csproj .
COPY service-a/Program.cs .

# Восстанавливаем и публикуем
RUN dotnet restore ServiceA.csproj
RUN dotnet publish ServiceA.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 5001
ENTRYPOINT ["dotnet", "ServiceA.dll"]
