FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Копируем файлы проекта
COPY gateway/Gateway.csproj .
COPY gateway/Program.cs .

# Восстанавливаем и публикуем
RUN dotnet restore Gateway.csproj
RUN dotnet publish Gateway.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 5000
ENTRYPOINT ["dotnet", "Gateway.dll"]
